name       : pianobar
version    : 2016.06.02
release    : 2
source     :
    - https://github.com/PromyLOPh/pianobar/archive/2016.06.02.tar.gz : 977d696c51d8e768be7b9a72480f1277cac99b3d007cd789e31364264dce25c2
license    : MIT
component  : multimedia.audio
summary    : Console-based pandora.com player
description: |
    pianobar is a console client for the personalized web radio Pandora.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(json-c)
    - pkgconfig(libavfilter)
    - pkgconfig(libcurl)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
